### PR TITLE
Cru-154 adds checksum for crucible and user wallet address

### PR DESCRIPTION
**Pull request by georgeweiler**

### CODE REVIEW

**Comment by joehawary** [comment]
Nice Job! This works perfectly!

Just been checking the preview, I think the crucible address was missed out in the Crucible Card and copy functions on the list view and crucible card :)

**Comment by georgeweiler** [comment]
that should be all of them @joehawary  :)

**Comment by joehawary** [comment]
Missed one 🤣
Screenshot 2021-06-14 at 07 04 58

**Comment by georgeweiler** [comment]
@joehawary thanks man, great catch. pushed up a fix.

**Review by joehawary — APPROVED** [review]
Nice! Great work :)

**Pull request merged**
