### PR TITLE
Added basic signature steps

### PR DESCRIPTION
**Pull request by nuurcodes**

### CODE REVIEW

**Comment by pakaplace** [comment]
Looks good but you may want to start at 1 if you're displaying step as a number

**Comment by nuurcodes** [comment]
> Looks good but you may want to start at 1 if you're displaying step as a number

I'm hiding the step UI if the step value is 0, maybe setting the initial step to null/undefined instead of 0 will make more sense

**Comment by nuurcodes** [comment]
Screenshot 2021-04-11 at 16 22 21
Screenshot 2021-04-11 at 16 22 32
Screenshot 2021-04-11 at 16 22 41
Screenshot 2021-04-11 at 16 23 22
Screenshot 2021-04-11 at 16 22 58

**Comment by pakaplace** [comment]
image
Tested the flow and it works great. The only thing is- could you add a Uniswap LP link to this description? As a user if I ran out of LP tokens and it'd be nice to have a link accessiible in the UI.

**Review by pakaplace — APPROVED** [review]

**Comment by nuurcodes** [comment]
> image
> Tested the flow and it works great. The only thing is- could you add a Uniswap LP link to this description? As a user if I ran out of LP tokens and it'd be nice to have a link accessiible in the UI.

@pakaplace We show the missing ingredients state when the user has no LP tokens so they would never see this screen (that includes both the `uniswap pool url` and `swap url`

**Pull request merged**
